export const bj_level = [
  "전체문제",
  "Bronze V",
  "Bronze IV",
  "Bronze III",
  "Bronze II",
  "Bronze I",
  "Silver V",
  "Silver IV",
  "Silver III",
  "Silver II",
  "Silver I",
  "Gold V",
  "Gold IV",
  "Gold III",
  "Gold II",
  "Gold I",
  "Platinum V",
  "Platinum IV",
  "Platinum III",
  "Platinum II",
  "Platinum I",
  "Diamond V",
  "Diamond IV",
  "Diamond III",
  "Diamond II",
  "Diamond I",
  "Ruby V",
  "Ruby IV",
  "Ruby III",
  "Ruby II",
  "Ruby I",
];

export const codeLanguage = (str: string | undefined) => {
  if (str === undefined) return "";

  if (str == "cpp") {
    return "C++";
  } else {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
};

interface MyObject {
  [key: string]: string;
}

export const algo_tag: MyObject = {
  수학: "124",
  Mathematics: "124",
  구현: "102",
  Implementation: "102",
  "다이나믹 프로그래밍": "25",
  "Dynamic Programming": "25",
  "자료 구조": "175",
  "Data Structures": "175",
  "그래프 이론": "7",
  "Graph Theory": "7",
  문자열: "158",
  String: "158",
  "그리디 알고리즘": "33",
  Greedy: "33",
  "브루트포스 알고리즘": "125",
  Bruteforcing: "125",
  "그래프 탐색": "11",
  "Graph Traversal": "11",
  정렬: "97",
  Sorting: "97",
  정수론: "95",
  "Number Theory": "95",
  기하학: "100",
  Geometry: "100",
  트리: "120",
  Tree: "120",
  "세그먼트 트리": "65",
  "Segment Tree": "65",
  "BOJ Book": "https://book.acmicpc.net/algorithm/sqrt-decomposition",
  "이분 탐색": "12",
  "Binary Search": "12",
  "애드 혹": "109",
  "Ad-hoc": "109",
  사칙연산: "121",
  Arithmetic: "121",
  "너비 우선 탐색": "126",
  "Breadth-first Search": "126",
  시뮬레이션: "141",
  Simulation: "141",
  "해 구성하기": "128",
  Constructive: "128",
  "누적 합": "139",
  "Prefix Sum": "139",
  조합론: "6",
  Combinatorics: "6",
  "깊이 우선 탐색": "127",
  "Depth-first Search": "127",
  "많은 조건 분기": "137",
  "Case Work": "137",
  비트마스킹: "14",
  Bitmask: "14",
  "해시를 사용한 집합과 맵": "136",
  "Set / Map By Hashing": "136",
  데이크스트라: "22",
  "Dijkstra's": "22",
  백트래킹: "5",
  Backtracking: "5",
  "트리를 사용한 집합과 맵": "74",
  "Set / Map By Trees": "74",
  스위핑: "106",
  Sweeping: "106",
  파싱: "96",
  Parsing: "96",
  "분리 집합": "81",
  "Disjoint Set": "81",
  "분할 정복": "24",
  "Divide And Conquer": "24",
  "트리에서의 다이나믹 프로그래밍": "92",
  "Dynamic Programming On Trees": "92",
  "우선순위 큐": "59",
  "Priority Queue": "59",
  스택: "71",
  Stack: "71",
  "두 포인터": "80",
  "Two-pointer": "80",
  "매개 변수 탐색": "170",
  "Parametric Search": "170",
  "게임 이론": "140",
  "Game Theory": "140",
  "소수 판정": "9",
  "Primality Test": "9",
  "최대 유량": "45",
  "Maximum Flow": "45",
  "느리게 갱신되는 세그먼트 트리": "66",
  "Segment Tree With Lazy Propagation": "66",
  "비트필드를 이용한 다이나믹 프로그래밍": "87",
  "Dynamic Programming Using Bitfield": "87",
  확률론: "177",
  "Probability Theory": "177",
  "분할 정복을 이용한 거듭제곱": "39",
  "Exponentiation By Squaring": "39",
  "임의 정밀도 / 큰 수 연산": "117",
  "Arbitrary Precision / Big Integers": "117",
  "오프라인 쿼리": "123",
  "Offline Queries": "123",
  재귀: "62",
  Recursion: "62",
  "배낭 문제": "148",
  Knapsack: "148",
  "에라토스테네스의 체": "67",
  "Sieve Of Eratosthenes": "67",
  "런타임 전의 전처리": "172",
  Precomputation: "172",
  "값 / 좌표 압축": "161",
  "Value / Coordinate Compression": "161",
  "최소 스패닝 트리": "49",
  "Minimum Spanning Tree": "49",
  "유클리드 호제법": "26",
  "Euclidean Algorithm": "26",
  "이분 매칭": "13",
  "Bipartite Matching": "13",
  "최소 공통 조상": "41",
  "Lowest Common Ancestor": "41",
  "위상 정렬": "78",
  "Topological Sorting": "78",
  "플로이드–워셜": "31",
  "Floyd–warshall": "31",
  선형대수학: "144",
  "Linear Algebra": "144",
  해싱: "8",
  Hashing: "8",
  "볼록 껍질": "20",
  "Convex Hull": "20",
  "포함 배제의 원리": "38",
  "Inclusion And Exclusion": "38",
  "강한 연결 요소": "76",
  "Strongly Connected Component": "76",
  "희소 배열": "84",
  "Sparse Table": "84",
  무작위화: "115",
  Randomization: "115",
  "고속 푸리에 변환": "28",
  "Fast Fourier Transform": "28",
  트라이: "79",
  Trie: "79",
  "작은 집합에서 큰 집합으로 합치는 테크닉": "169",
  "Smaller To Larger Technique": "169",
  "제곱근 분할법": "130",
  "Square Root Decomposition": "130",
  "최소 비용 최대 유량": "48",
  "Minimum Cost Maximum Flow": "48",
  "접미사 배열과 lcp 배열": "77",
  "Suffix Array And Lcp Array": "77",
  덱: "73",
  Deque: "73",
  "볼록 껍질을 이용한 최적화": "89",
  "Convex Hull Trick": "89",
  "선분 교차 판정": "42",
  "Line Segment Intersection Check": "42",
  "3차원 기하학": "131",
  "Geometry; 3d": "131",
  미적분학: "111",
  Calculus: "111",
  휴리스틱: "142",
  Heuristics: "142",
  "중간에서 만나기": "46",
  "Meet In The Middle": "46",
  "스프라그–그런디 정리": "70",
  "Sprague–grundy Theorem": "70",
  "오일러 경로 테크닉": "150",
  "Euler Tour Technique": "150",
  "슬라이딩 윈도우": "68",
  "Sliding Window": "68",
  센트로이드: "188",
  Centroid: "188",
  kmp: "40",
  "Knuth–morris–pratt": "40",
  "가장 긴 증가하는 부분 수열: o(n log n)": "43",
  "Longest Increasing Sequence In O(n Log N)": "43",
  "피타고라스 정리": "60",
  "Pythagoras Theorem": "60",
  "센트로이드 분할": "18",
  "Centroid Decomposition": "18",
  "가우스 소거법": "32",
  "Gaussian Elimination": "32",
  "heavy-light 분할": "35",
  "Heavy-light Decomposition": "35",
  "순열 사이클 분할": "171",
  "Permutation Cycle Decomposition": "171",
  "삼분 탐색": "101",
  "Ternary Search": "101",
  "비트 집합": "152",
  "Bit Set": "152",
  "모듈로 곱셈 역원": "164",
  "Modular Multiplicative Inverse": "164",
  "최대 유량 최소 컷 정리": "167",
  "Max-flow Min-cut Theorem": "167",
  큐: "72",
  Queue: "72",
  "오일러 경로": "93",
  "Eulerian Path / Circuit": "93",
  물리학: "116",
  Physics: "116",
  "단절점과 단절선": "4",
  "Articulation Points And Bridges": "4",
  "2-sat": "1",
  "외판원 순회 문제": "138",
  "Travelling Salesman Problem": "138",
  "퍼시스턴트 세그먼트 트리": "55",
  "Persistent Segment Tree": "55",
  "페르마의 소정리": "29",
  "Fermat's Little Theorem": "29",
  "0-1 너비 우선 탐색": "176",
  "0-1 Bfs": "176",
  "기댓값의 선형성": "179",
  "Linearity Of Expectation": "179",
  "다각형의 넓이": "3",
  "Area Of A Polygon": "3",
  선인장: "143",
  Cactus: "143",
  "중국인의 나머지 정리": "19",
  "Chinese Remainder Theorem": "19",
  "mo's": "50",
  "Mo's": "50",
  "이중 연결 요소": "153",
  "Biconnected Component": "153",
  "평면 그래프": "168",
  "Planar Graph": "168",
  "벨만–포드": "10",
  "Bellman–ford": "10",
  "오일러 피 함수": "151",
  "Euler Totient Function": "151",
  "확장 유클리드 호제법": "27",
  "Extended Euclidean Algorithm": "27",
  "병렬 이분 탐색": "54",
  "Parallel Binary Search": "54",
  "볼록 다각형 내부의 점 판정": "56",
  "Point In Convex Polygon Check": "56",
  "분할 정복을 사용한 최적화": "91",
  "Divide And Conquer Optimization": "91",
  "연결 리스트": "154",
  "Linked List": "154",
  "비둘기집 원리": "189",
  "Pigeonhole Principle": "189",
  "이분 그래프": "197",
  "Bipartite Graph": "197",
  "회전하는 캘리퍼스": "64",
  "Rotating Calipers": "64",
  "스플레이 트리": "69",
  "Splay Tree": "69",
  "벌리캠프–매시": "110",
  "Berlekamp–massey": "110",
  "머지 소트 트리": "155",
  "Merge Sort Tree": "155",
  "다차원 세그먼트 트리": "166",
  "Multidimensional Segment Tree": "166",
  "정규 표현식": "63",
  "Regular Expression": "63",
  "오일러 지표 (χ=v-e+f)": "119",
  "Euler Characteristic (χ=v-e+f)": "119",
  "아호-코라식": "2",
  "Aho-corasick": "2",
  "덱을 이용한 다이나믹 프로그래밍": "108",
  "Dynamic Programming Using A Deque": "108",
  매내처: "44",
  "Manacher's": "44",
  "링크/컷 트리": "98",
  "Link/cut Tree": "98",
  "함수 개형을 이용한 최적화": "157",
  "Slope Trick": "157",
  "커넥션 프로파일을 이용한 다이나믹 프로그래밍": "107",
  "Dynamic Programming Using Connection Profile": "107",
  "라빈–카프": "61",
  "Rabin–karp": "61",
  "뫼비우스 반전 공식": "51",
  "Möbius Inversion": "51",
  "트리 동형 사상": "145",
  "Tree Isomorphism": "145",
  "반평면 교집합": "190",
  "Half Plane Intersection": "190",
  "폴라드 로": "58",
  "Pollard Rho": "58",
  "홀의 결혼 정리": "34",
  "Hall's Theorem": "34",
  "밀러–라빈 소수 판별법": "47",
  "Miller–rabin": "47",
  수치해석: "122",
  "Numerical Analysis": "122",
  서큘레이션: "191",
  Circulation: "191",
  헝가리안: "36",
  Hungarian: "36",
  "선형 계획법": "103",
  "Linear Programming": "103",
  통계학: "178",
  Statistics: "178",
  "오프라인 동적 연결성 판정": "52",
  "Offline Dynamic Connectivity": "52",
  "오목 다각형 내부의 점 판정": "57",
  "Point In Non-convex Polygon Check": "57",
  "aliens 트릭": "134",
  "Aliens Trick": "134",
  "담금질 기법": "184",
  "Simulated Annealing": "184",
  쌍대성: "180",
  Duality: "180",
  "쌍대 그래프": "181",
  "Dual Graph": "181",
  "보로노이 다이어그램": "82",
  "Voronoi Diagram": "82",
  "뤼카 정리": "113",
  "Lucas Theorem": "113",
  "부분집합의 합 다이나믹 프로그래밍": "207",
  "Sum Over Subsets Dynamic Programming": "207",
  매트로이드: "104",
  Matroid: "104",
  키타마사: "112",
  Kitamasa: "112",
  "생성 함수": "198",
  "Generating Function": "198",
  "일반적인 매칭": "15",
  "General Matching": "15",
  "이산 로그": "146",
  "Discrete Logarithm": "146",
  "최소 외접원": "162",
  "Minimum Enclosing Circle": "162",
  "트리 분할": "204",
  "Tree Decomposition": "204",
  "번사이드 보조정리": "16",
  "Burnside's Lemma": "16",
  "트리 압축": "193",
  "Tree Compression": "193",
  "회문 트리": "53",
  "Palindrome Tree": "53",
  "양방향 탐색": "129",
  "Bidirectional Search": "129",
  "도미네이터 트리": "135",
  "Dominator Tree": "135",
  "안정 결혼 문제": "192",
  "Stable Marriage Problem": "192",
  z: "83",
  Z: "83",
  "크누스 최적화": "90",
  "Knuth Optimization": "90",
  "단조 큐를 이용한 최적화": "165",
  "Monotone Queue Optimization": "165",
  "utf-8 입력 처리": "199",
  "Utf-8 Inputs": "199",
  "4차원 이상의 기하학": "132",
  "Geometry; Hyperdimensional": "132",
  "이산 제곱근": "147",
  "Discrete Square Root": "147",
  로프: "159",
  Rope: "159",
  "춤추는 링크": "173",
  "Dancing Links": "173",
  "크누스 x": "174",
  "Knuth's X": "174",
  "접미사 트리": "182",
  "Suffix Tree": "182",
  "픽의 정리": "187",
  "Pick's Theorem": "187",
  "유향 최소 신장 트리": "23",
  "Directed Minimum Spanning Tree": "23",
  "스토어–바그너": "75",
  "Stoer–wagner": "75",
  "베이즈 정리": "114",
  "Bayes Theorem": "114",
  히르쉬버그: "163",
  "Hirschberg's": "163",
  "그린 정리": "183",
  "Green's Theorem": "183",
  차수열: "200",
  "Degree Sequence": "200",
  "현 그래프": "201",
  "Chordal Graph": "201",
  "데카르트 트리": "206",
  "Cartesian Tree": "206",
  "델로네 삼각분할": "21",
  "Delaunay Triangulation": "21",
  "탑 트리": "105",
  "Top Tree": "105",
  "보이어–무어 다수결 투표": "160",
  "Boyer–moore Majority Vote": "160",
  "경사 하강법": "208",
  "Gradient Descent": "208",
  "도형에서의 불 연산": "202",
  "Boolean Operations On Geometric Objects": "202",
  "하켄부시 게임": "205",
  Hackenbush: "205",
  "레드-블랙 트리": "94",
  "Red-black Tree": "94",
  "이산 k제곱근": "149",
  "Discrete K-th Root": "149",
  "차분 공격": "185",
  "Differential Cryptanalysis": "185",
  "a*": "186",
  "A*": "186",
  "생일 문제": "203",
  "Birthday Problem": "203",
  "다항식 보간법": "209",
  "Polynomial Interpolation": "209",
};
